strictness: veryhigh
test-warnings: True
doc-warnings: false

ignore-paths:
  - build
  - dist

max-line-length: 120

pylint:
  disable:
    - logging-fstring-interpolation
    - missing-class-docstring
    - missing-module-docstring
    - too-few-public-methods
    - too-many-arguments
    - too-many-instance-attributes
    - abstract-method                   # Disabled during early stage of development
    - unused-argument                   # Disabled during early stage of development

pep8:
  disable:
    - E203  # whitespace before ':' (https://www.flake8rules.com/rules/E203.html, but Black disagree with it: https://github.com/psf/black/issues/315)

pep257:
  disable:
    - D102  # Missing docstring in public method (https://pep257.readthedocs.io/en/latest/error_codes.html)

mypy:
  run: true
  options:
    ignore-missing-imports: true
